# Generated by Django 4.1.3 on 2023-02-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_Name', models.TextField()),
                ('Module_Image', models.TextField()),
                ('Module_Link', models.TextField()),
                ('Module_SeqNo', models.PositiveIntegerField(default=1, unique=True)),
            ],
        ),
    ]
